#pragma once
#include "TextureResource.h"
#include "Loadable.h"
#include <memory>

class Texture : public Loadable
{
	// Texture Resource Config
	std::shared_ptr<TextureResource> tr;

	// TextureId generated by glGenTextures()
	GLint textureId;

public:
	// Constructor
	Texture(std::shared_ptr<TextureResource> tr = nullptr);

	// Destructor
	virtual ~Texture();

	// Getters and setters
	GLint getTextureId() const;
	void setTextureId(GLint id);

	std::shared_ptr<TextureResource> getTextureResource();
	void setTextureResource(std::shared_ptr<TextureResource> textureResource);

	// Inherited via Loadable
	virtual void load() override;
};